version: "3.8"

services:
  notification-service:
    build: ./Notification_Service/
    container_name: notification-service
    ports:
      - "50051:50051"
    depends_on:
      - rabbitmq

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
