version: "3.8"

services:
  user-service:
    build: ./User_Service
    container_name: user-service
    ports:
      - "50052:50052"
      - "8080:8080"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=orbiappuser
      - MYSQL_PASSWORD=apppassword
      - MYSQL_DATABASE=usersdb
    depends_on:
      - mysql
      - rabbitmq
      - notification-service

  notification-service:
    build: ./Notification_Service/
    container_name: notification-service
    ports:
      - "50051:50051"
    depends_on:
      - rabbitmq

  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD=rootpassword
      MYSQL_DATABASE=usersdb
      MYSQL_USER=orbiappuser
      MYSQL_PASSWORD=apppassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  mysql_data:
    driver: local
